version: "3.9"
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:14.1
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: names_db
    ports: 
      - '2345:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  api:
    container_name: node
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - postgres_db
    ports:
      - '8001:8001'
    volumes:
      - ./backend/src:/app/src


 
volumes:
  postgres_db: